### ISSUE TITLE
rotarycontroller code

### ISSUE THREAD

**Issue by soundog5** [squarefrog/teensy-midi-encoder-box#2]
Paul -- could you ensure rotarycontroller.ino (for teensy-midi-encoder-box) is correct and current? It won't verify/compile without a boatload of errors using the current teensyarduino app. Further, there seems to be a lot of superfluous code in the file. Do you perchance have a slimmed down or updated version? Cheers, John

**Comment by squarefrog** [comment]
You need to set your USB type - Tools > USB Type > MIDI.

After setting that it compiles fine for me with one warning: 

```
In file included from /private/var/folders/qb/qf9kj1px6sv90zv0_lt646d80000gp/T/AppTranslocation/A6217479-27C4-4B32-9057-BF047F700A5D/d/Teensyduino.app/Contents/Java/hardware/teensy/avr/cores/teensy/usb.c:10:0:
/private/var/folders/qb/qf9kj1px6sv90zv0_lt646d80000gp/T/AppTranslocation/A6217479-27C4-4B32-9057-BF047F700A5D/d/Teensyduino.app/Contents/Java/hardware/teensy/avr/cores/teensy/../usb_midi/usb.c:125:50: warning: missing terminating ' character
  but when I add them, MIDI breaks on Linux (haven't tried Mac and
```

**Comment by soundog5** [comment]
Thank you. That fixed everything. FYI, I'm on Mac OSX Catalina running latest Teensyduino and your code compiles and runs without error. Cheers!!
